In [1]:
# Bloco 1 - Importar a base de rotas com cidade e estado

from pathlib import Path
import pandas as pd


def obter_pasta_do_notebook():
    return Path.cwd()


def importar_csv_mesma_pasta(nome_arquivo, nome_base, colunas=None, sep=",", engine=None):
    try:
        pasta_notebook = obter_pasta_do_notebook()
        caminho_arquivo = pasta_notebook / nome_arquivo

        argumentos = {
            "filepath_or_buffer": caminho_arquivo,
            "sep": sep,
            "encoding": "utf-8-sig",
            "usecols": colunas
        }

        if engine is not None:
            argumentos["engine"] = engine
        else:
            argumentos["low_memory"] = False

        df = pd.read_csv(**argumentos)
        df.columns = df.columns.str.strip()

        print(f"Base '{nome_base}' importada com sucesso!")
        print(f"Arquivo importado: {caminho_arquivo}")
        print(f"Quantidade de linhas: {df.shape[0]}")
        print(f"Quantidade de colunas: {df.shape[1]}")
        print()

        return df

    except FileNotFoundError:
        print(f"Erro: arquivo da base '{nome_base}' não encontrado.")
        print(f"Verifique se o arquivo '{nome_arquivo}' está na mesma pasta do notebook.")
        return None

    except Exception as erro:
        print(f"Erro ao importar a base '{nome_base}'.")
        print(f"Detalhes do erro: {erro}")
        return None


def inserir_cidade_estado(df_rotas, df_municipios):
    df_rotas = df_rotas.copy()
    df_municipios = df_municipios.copy()

    df_rotas.columns = df_rotas.columns.str.strip()
    df_municipios.columns = df_municipios.columns.str.strip()

    colunas_municipios_necessarias = [
        "Código Município Completo",
        "Nome_Município",
        "Nome_UF"
    ]

    colunas_faltantes = [
        coluna for coluna in colunas_municipios_necessarias
        if coluna not in df_municipios.columns
    ]

    if colunas_faltantes:
        print("Erro: algumas colunas necessárias não foram encontradas na base de municípios.")
        print("Colunas faltantes:", colunas_faltantes)
        return None

    df_rotas["codigo_cidade"] = pd.to_numeric(
        df_rotas["codigo_cidade"],
        errors="coerce"
    ).astype("Int64")

    df_municipios["Código Município Completo"] = pd.to_numeric(
        df_municipios["Código Município Completo"],
        errors="coerce"
    ).astype("Int64")

    df_municipios_resumido = (
        df_municipios[
            [
                "Código Município Completo",
                "Nome_Município",
                "Nome_UF"
            ]
        ]
        .drop_duplicates(subset=["Código Município Completo"], keep="first")
        .rename(
            columns={
                "Código Município Completo": "codigo_cidade",
                "Nome_Município": "nome_cidade",
                "Nome_UF": "estado"
            }
        )
    )

    df_rotas_transformado = df_rotas.merge(
        df_municipios_resumido,
        on="codigo_cidade",
        how="left"
    )

    colunas = list(df_rotas_transformado.columns)
    colunas.remove("nome_cidade")
    colunas.remove("estado")

    posicao_codigo_cidade = colunas.index("codigo_cidade")
    colunas.insert(posicao_codigo_cidade + 1, "nome_cidade")
    colunas.insert(posicao_codigo_cidade + 2, "estado")

    df_rotas_transformado = df_rotas_transformado[colunas]

    print("Dados transformados com sucesso!")
    print(
        "Quantidade de rotas sem cidade/estado encontradas:",
        df_rotas_transformado["nome_cidade"].isna().sum()
    )

    return df_rotas_transformado


nome_arquivo_rotas = "script_03_rotas.csv"
nome_arquivo_municipios = "Lista de Municipios IBGE.csv"

colunas_rotas = [
    "codigo_cidade",
    "id_rota",
    "da_porteira",
    "da_mataburro",
    "da_colchete",
    "da_atoleiro",
    "da_ponterustica",
    "tipo",
    "shape"
]

df_rotas = importar_csv_mesma_pasta(
    nome_arquivo_rotas,
    "rotas",
    colunas=colunas_rotas,
    sep="," 
)

df_municipios = importar_csv_mesma_pasta(
    nome_arquivo_municipios,
    "municípios",
    sep=None,
    engine="python"
)

if df_rotas is not None and df_municipios is not None:
    df_rotas_transformado = inserir_cidade_estado(df_rotas, df_municipios)

    if df_rotas_transformado is not None:
        display(df_rotas_transformado)

        # Exporta o DataFrame transformado para CSV na mesma pasta do notebook
        pasta_notebook = obter_pasta_do_notebook()
        nome_arquivo_saida = "script_03_rotas_consolidado.csv"
        caminho_arquivo_saida = pasta_notebook / nome_arquivo_saida

        df_rotas_transformado.to_csv(
            caminho_arquivo_saida,
            index=False,
            encoding="utf-8-sig"
        )

        print(f"\nArquivo exportado com sucesso!")
        print(f"Caminho: {caminho_arquivo_saida}")

Base 'rotas' importada com sucesso!
Arquivo importado: d:\Matheus\OneDrive\Trabalho\00-UFG\Transporte escolar\Frente de indicadores\Dados SETE 2026\Dados dados sete consolidados\script_03_rotas.csv
Quantidade de linhas: 82887
Quantidade de colunas: 9

Base 'municípios' importada com sucesso!
Arquivo importado: d:\Matheus\OneDrive\Trabalho\00-UFG\Transporte escolar\Frente de indicadores\Dados SETE 2026\Dados dados sete consolidados\Lista de Municipios IBGE.csv
Quantidade de linhas: 5572
Quantidade de colunas: 13

Dados transformados com sucesso!
Quantidade de rotas sem cidade/estado encontradas: 0

,codigo_cidade,nome_cidade,estado,id_rota,da_porteira,da_mataburro,da_colchete,da_atoleiro,da_ponterustica,shape,tipo
0,5212501,Luziânia,Goiás,85313,N,N,N,N,N,NaN,1
1,3113305,Carangola,Minas Gerais,94777,N,N,N,N,N,NaN,1
2,1100098,Espigão D'Oeste,Rondônia,1,N,N,N,N,N,NaN,1
3,1100106,Guajará-Mirim,Rondônia,1,N,N,N,N,N,NaN,2
4,1100130,Machadinho D'Oeste,Rondônia,1,N,N,N,N,N,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
82882,2704708,Marechal Deodoro,Alagoas,173720,N,N,N,N,N,"{""type"":""FeatureCollection"",""features"":[{""type...",1
82883,4312708,Nonoai,Rio Grande do Sul,150978,N,N,N,N,N,"{""type"":""FeatureCollection"",""features"":[{""type...",1
82884,4125506,São José dos Pinhais,Paraná,173722,N,N,N,N,N,NaN,1
82885,3518404,Guaratinguetá,São Paulo,10,S,N,N,S,S,NaN,1
82886,3520400,Ilhabela,São Paulo,172985,N,N,N,N,N,NaN,1

Arquivo exportado com sucesso!
Caminho: d:\Matheus\OneDrive\Trabalho\00-UFG\Transporte escolar\Frente de indicadores\Dados SETE 2026\Dados dados sete consolidados\script_03_rotas_consolidado.csv

In [2]:
# Bloco 2 - Preparar a base de rotas para consolidação

df_consolidacao = df_rotas_transformado.copy()

df_consolidacao["estado"] = df_consolidacao["estado"].fillna("Não identificado")

colunas_dificuldade = [
    "da_porteira",
    "da_mataburro",
    "da_colchete",
    "da_atoleiro",
    "da_ponterustica"
]

for coluna in colunas_dificuldade:
    df_consolidacao[coluna] = (
        df_consolidacao[coluna]
        .astype(str)
        .str.strip()
        .str.upper()
    )

df_consolidacao["tipo"] = pd.to_numeric(
    df_consolidacao["tipo"],
    errors="coerce"
).astype("Int64")

print("Base de rotas preparada para consolidação.")
display(df_consolidacao.head())

Base de rotas preparada para consolidação.

,codigo_cidade,nome_cidade,estado,id_rota,da_porteira,da_mataburro,da_colchete,da_atoleiro,da_ponterustica,shape,tipo
0,5212501,Luziânia,Goiás,85313,N,N,N,N,N,NaN,1
1,3113305,Carangola,Minas Gerais,94777,N,N,N,N,N,NaN,1
2,1100098,Espigão D'Oeste,Rondônia,1,N,N,N,N,N,NaN,1
3,1100106,Guajará-Mirim,Rondônia,1,N,N,N,N,N,NaN,2
4,1100130,Machadinho D'Oeste,Rondônia,1,N,N,N,N,N,NaN,1

In [3]:
# Bloco 3 - Função para consolidar dificuldades de acesso por estado

def consolidar_coluna_sim_nao_por_estado(df, coluna, nome_tabela):
    df_temp = df.copy()

    df_temp[coluna] = df_temp[coluna].astype(str).str.strip().str.upper()
    df_temp[f"tem_{coluna}"] = df_temp[coluna] == "S"

    tabela = (
        df_temp
        .groupby("estado")
        .agg(
            total_rotas=("id_rota", "size"),
            com=("tem_" + coluna, "sum"),
            sem=("tem_" + coluna, lambda x: (~x).sum())
        )
        .reset_index()
        .rename(
            columns={
                "com": f"com_{coluna}",
                "sem": f"sem_{coluna}"
            }
        )
        .sort_values("estado")
    )

    print(nome_tabela)
    display(tabela)

    return tabela

In [4]:
# Bloco 4 - Consolidar dificuldades de acesso por estado

tabela_porteira = consolidar_coluna_sim_nao_por_estado(
    df_consolidacao,
    "da_porteira",
    "Tabela consolidada de porteira por estado:"
)

tabela_mataburro = consolidar_coluna_sim_nao_por_estado(
    df_consolidacao,
    "da_mataburro",
    "Tabela consolidada de mata-burro por estado:"
)

tabela_colchete = consolidar_coluna_sim_nao_por_estado(
    df_consolidacao,
    "da_colchete",
    "Tabela consolidada de colchete por estado:"
)

tabela_atoleiro = consolidar_coluna_sim_nao_por_estado(
    df_consolidacao,
    "da_atoleiro",
    "Tabela consolidada de atoleiro por estado:"
)

tabela_ponterustica = consolidar_coluna_sim_nao_por_estado(
    df_consolidacao,
    "da_ponterustica",
    "Tabela consolidada de ponte rústica por estado:"
)

Tabela consolidada de porteira por estado:

                 estado  total_rotas  com_da_porteira  sem_da_porteira
0                  Acre          128                5              123
1               Alagoas         1345               31             1314
2                 Amapá           47                0               47
3              Amazonas          332                0              332
4                 Bahia        10080              415             9665
5                 Ceará         4382              245             4137
6      Distrito Federal            5                0                5
7        Espírito Santo         1971               34             1937
8                 Goiás         2491              646             1845
9              Maranhão         1968              187             1781
10          Mato Grosso         2199              167             2032
11   Mato Grosso do Sul         1245              266              979
12         Minas Gerais        15679             2111            13568
13               Paraná         6095              142             5953
14              Paraíba         1715              168             1547
15                 Pará         3235              252             2983
16           Pernambuco         6139               97             6042
17                Piauí         1928               61             1867
18  Rio Grande do Norte         1188              125             1063
19    Rio Grande do Sul         6522              107             6415
20       Rio de Janeiro         1078               51             1027
21             Rondônia         1362               28             1334
22              Roraima           62                0               62
23       Santa Catarina         2839               52             2787
24              Sergipe          574               54              520
25            São Paulo         6632              500             6132
26            Tocantins         1646              317             1329

Tabela consolidada de mata-burro por estado:

                 estado  total_rotas  com_da_mataburro  sem_da_mataburro
0                  Acre          128                 0               128
1               Alagoas         1345                15              1330
2                 Amapá           47                 0                47
3              Amazonas          332                 0               332
4                 Bahia        10080               361              9719
5                 Ceará         4382               420              3962
6      Distrito Federal            5                 0                 5
7        Espírito Santo         1971                45              1926
8                 Goiás         2491               705              1786
9              Maranhão         1968               212              1756
10          Mato Grosso         2199               254              1945
11   Mato Grosso do Sul         1245               218              1027
12         Minas Gerais        15679              3563             12116
13               Paraná         6095                65              6030
14              Paraíba         1715               215              1500
15                 Pará         3235               178              3057
16           Pernambuco         6139                65              6074
17                Piauí         1928               146              1782
18  Rio Grande do Norte         1188               161              1027
19    Rio Grande do Sul         6522               180              6342
20       Rio de Janeiro         1078                35              1043
21             Rondônia         1362                58              1304
22              Roraima           62                 0                62
23       Santa Catarina         2839               121              2718
24              Sergipe          574                43               531
25            São Paulo         6632               468              6164
26            Tocantins         1646               368              1278

Tabela consolidada de colchete por estado:

                 estado  total_rotas  com_da_colchete  sem_da_colchete
0                  Acre          128                0              128
1               Alagoas         1345                6             1339
2                 Amapá           47                0               47
3              Amazonas          332                0              332
4                 Bahia        10080              154             9926
5                 Ceará         4382               82             4300
6      Distrito Federal            5                0                5
7        Espírito Santo         1971                5             1966
8                 Goiás         2491              411             2080
9              Maranhão         1968              169             1799
10          Mato Grosso         2199               96             2103
11   Mato Grosso do Sul         1245              102             1143
12         Minas Gerais        15679              919            14760
13               Paraná         6095               64             6031
14              Paraíba         1715               53             1662
15                 Pará         3235              146             3089
16           Pernambuco         6139               40             6099
17                Piauí         1928               47             1881
18  Rio Grande do Norte         1188               52             1136
19    Rio Grande do Sul         6522               47             6475
20       Rio de Janeiro         1078                5             1073
21             Rondônia         1362                1             1361
22              Roraima           62                0               62
23       Santa Catarina         2839                7             2832
24              Sergipe          574               24              550
25            São Paulo         6632              175             6457
26            Tocantins         1646              301             1345

Tabela consolidada de atoleiro por estado:

                 estado  total_rotas  com_da_atoleiro  sem_da_atoleiro
0                  Acre          128               12              116
1               Alagoas         1345              135             1210
2                 Amapá           47               13               34
3              Amazonas          332               30              302
4                 Bahia        10080              895             9185
5                 Ceará         4382              667             3715
6      Distrito Federal            5                0                5
7        Espírito Santo         1971              103             1868
8                 Goiás         2491              517             1974
9              Maranhão         1968              561             1407
10          Mato Grosso         2199              262             1937
11   Mato Grosso do Sul         1245              277              968
12         Minas Gerais        15679             2043            13636
13               Paraná         6095              320             5775
14              Paraíba         1715              319             1396
15                 Pará         3235              398             2837
16           Pernambuco         6139              364             5775
17                Piauí         1928              283             1645
18  Rio Grande do Norte         1188              146             1042
19    Rio Grande do Sul         6522              584             5938
20       Rio de Janeiro         1078               90              988
21             Rondônia         1362              138             1224
22              Roraima           62                2               60
23       Santa Catarina         2839              303             2536
24              Sergipe          574              157              417
25            São Paulo         6632              610             6022
26            Tocantins         1646              295             1351

Tabela consolidada de ponte rústica por estado:

                 estado  total_rotas  com_da_ponterustica  sem_da_ponterustica
0                  Acre          128                    9                  119
1               Alagoas         1345                   49                 1296
2                 Amapá           47                    2                   45
3              Amazonas          332                   34                  298
4                 Bahia        10080                  234                 9846
5                 Ceará         4382                  110                 4272
6      Distrito Federal            5                    0                    5
7        Espírito Santo         1971                   32                 1939
8                 Goiás         2491                  473                 2018
9              Maranhão         1968                  273                 1695
10          Mato Grosso         2199                  289                 1910
11   Mato Grosso do Sul         1245                  164                 1081
12         Minas Gerais        15679                 1873                13806
13               Paraná         6095                  182                 5913
14              Paraíba         1715                   33                 1682
15                 Pará         3235                  394                 2841
16           Pernambuco         6139                   68                 6071
17                Piauí         1928                   54                 1874
18  Rio Grande do Norte         1188                   27                 1161
19    Rio Grande do Sul         6522                  341                 6181
20       Rio de Janeiro         1078                   43                 1035
21             Rondônia         1362                  319                 1043
22              Roraima           62                    4                   58
23       Santa Catarina         2839                  206                 2633
24              Sergipe          574                   29                  545
25            São Paulo         6632                  248                 6384
26            Tocantins         1646                  211                 1435

In [5]:
# Bloco 5 - Consolidar tipo de rota por estado
# tipo: 1 - Rodoviária; 2 - Aquaviária; 3 - Mista

tabela_tipo_rota = (
    df_consolidacao
    .groupby("estado")
    .agg(
        total_rotas=("id_rota", "size"),
        rotas_rodoviarias=("tipo", lambda x: (x == 1).sum()),
        rotas_aquaviarias=("tipo", lambda x: (x == 2).sum()),
        rotas_mistas=("tipo", lambda x: (x == 3).sum()),
        rotas_tipo_nao_identificado=("tipo", lambda x: (~x.isin([1, 2, 3])).sum())
    )
    .reset_index()
    .sort_values("estado")
)

print("Tabela consolidada de tipo de rota por estado:")
display(tabela_tipo_rota)

Tabela consolidada de tipo de rota por estado:

,estado,total_rotas,rotas_rodoviarias,rotas_aquaviarias,rotas_mistas,rotas_tipo_nao_identificado
0,Acre,128,98,30,0,0
1,Alagoas,1345,1196,5,144,0
2,Amapá,47,36,11,0,0
3,Amazonas,332,124,208,0,0
4,Bahia,10080,9475,24,581,0
5,Ceará,4382,3908,1,473,0
6,Distrito Federal,5,5,0,0,0
7,Espírito Santo,1971,1848,1,122,0
8,Goiás,2491,2364,2,125,0
9,Maranhão,1968,1698,12,258,0
10,Mato Grosso,2199,2112,2,85,0
11,Mato Grosso do Sul,1245,1204,6,35,0
12,Minas Gerais,15679,15075,39,565,0
13,Paraná,6095,6029,5,61,0
14,Paraíba,1715,1542,0,173,0
15,Pará,3235,1870,1295,70,0
16,Pernambuco,6139,5620,29,490,0
17,Piauí,1928,1803,2,123,0
18,Rio Grande do Norte,1188,1096,1,91,0
19,Rio Grande do Sul,6522,6369,5,148,0
20,Rio de Janeiro,1078,1054,1,23,0
21,Rondônia,1362,1273,4,85,0
22,Roraima,62,62,0,0,0
23,Santa Catarina,2839,2592,2,245,0
24,Sergipe,574,553,1,20,0
25,São Paulo,6632,6468,5,159,0
26,Tocantins,1646,1142,2,502,0

In [6]:
# Bloco 6 - Consolidar rotas com e sem georreferenciamento por estado
# Considera rota georreferenciada quando a coluna shape está preenchida

df_consolidacao["tem_georreferenciamento"] = df_consolidacao["shape"].notna()

tabela_georreferenciamento = (
    df_consolidacao
    .groupby("estado")
    .agg(
        total_rotas=("id_rota", "size"),
        rotas_geoferenciadas=("tem_georreferenciamento", "sum"),
        rotas_nao_georeferenciadas=("tem_georreferenciamento", lambda x: (~x).sum())
    )
    .reset_index()
    .sort_values("estado")
)

print("Tabela consolidada de rotas com e sem georreferenciamento por estado:")
display(tabela_georreferenciamento)

Tabela consolidada de rotas com e sem georreferenciamento por estado:

,estado,total_rotas,rotas_geoferenciadas,rotas_nao_georeferenciadas
0,Acre,128,24,104
1,Alagoas,1345,762,583
2,Amapá,47,1,46
3,Amazonas,332,191,141
4,Bahia,10080,3748,6332
5,Ceará,4382,586,3796
6,Distrito Federal,5,3,2
7,Espírito Santo,1971,622,1349
8,Goiás,2491,887,1604
9,Maranhão,1968,505,1463
10,Mato Grosso,2199,697,1502
11,Mato Grosso do Sul,1245,483,762
12,Minas Gerais,15679,5855,9824
13,Paraná,6095,3893,2202
14,Paraíba,1715,284,1431
15,Pará,3235,595,2640
16,Pernambuco,6139,3036,3103
17,Piauí,1928,694,1234
18,Rio Grande do Norte,1188,385,803
19,Rio Grande do Sul,6522,3068,3454
20,Rio de Janeiro,1078,321,757
21,Rondônia,1362,500,862
22,Roraima,62,26,36
23,Santa Catarina,2839,1462,1377
24,Sergipe,574,300,274
25,São Paulo,6632,1801,4831
26,Tocantins,1646,897,749

In [7]:
# Bloco 7 - Consolidar todas as tabelas e exportar em Excel

from functools import reduce


def consolidar_tabelas_por_estado(tabelas):
    tabelas_preparadas = []

    for indice, tabela in enumerate(tabelas):
        tabela_temp = tabela.copy()

        if indice > 0 and "total_rotas" in tabela_temp.columns:
            tabela_temp = tabela_temp.drop(columns=["total_rotas"])

        tabelas_preparadas.append(tabela_temp)

    tabela_final = reduce(
        lambda esquerda, direita: esquerda.merge(
            direita,
            on="estado",
            how="outer"
        ),
        tabelas_preparadas
    )

    return tabela_final.sort_values("estado").reset_index(drop=True)


tabelas_para_consolidar = [
    tabela_porteira,
    tabela_mataburro,
    tabela_colchete,
    tabela_atoleiro,
    tabela_ponterustica,
    tabela_tipo_rota,
    tabela_georreferenciamento
]

tabela_consolidada_final = consolidar_tabelas_por_estado(tabelas_para_consolidar)

pasta_notebook = obter_pasta_do_notebook()
nome_arquivo_excel = "Consolidação 03 - script_03_rotas.xlsx"
caminho_arquivo_excel = pasta_notebook / nome_arquivo_excel

tabela_consolidada_final.to_excel(
    caminho_arquivo_excel,
    index=False,
    sheet_name="consolidado"
)

print("Tabela consolidada final exportada com sucesso!")
print(f"Arquivo Excel exportado: {caminho_arquivo_excel}")

display(tabela_consolidada_final)

Tabela consolidada final exportada com sucesso!
Arquivo Excel exportado: d:\Matheus\OneDrive\Trabalho\00-UFG\Transporte escolar\Frente de indicadores\Dados SETE 2026\Dados dados sete consolidados\Consolidação 03 - script_03_rotas.xlsx

,estado,total_rotas,com_da_porteira,sem_da_porteira,com_da_mataburro,sem_da_mataburro,com_da_colchete,sem_da_colchete,com_da_atoleiro,sem_da_atoleiro,com_da_ponterustica,sem_da_ponterustica,rotas_rodoviarias,rotas_aquaviarias,rotas_mistas,rotas_tipo_nao_identificado,rotas_geoferenciadas,rotas_nao_georeferenciadas
0,Acre,128,5,123,0,128,0,128,12,116,9,119,98,30,0,0,24,104
1,Alagoas,1345,31,1314,15,1330,6,1339,135,1210,49,1296,1196,5,144,0,762,583
2,Amapá,47,0,47,0,47,0,47,13,34,2,45,36,11,0,0,1,46
3,Amazonas,332,0,332,0,332,0,332,30,302,34,298,124,208,0,0,191,141
4,Bahia,10080,415,9665,361,9719,154,9926,895,9185,234,9846,9475,24,581,0,3748,6332
5,Ceará,4382,245,4137,420,3962,82,4300,667,3715,110,4272,3908,1,473,0,586,3796
6,Distrito Federal,5,0,5,0,5,0,5,0,5,0,5,5,0,0,0,3,2
7,Espírito Santo,1971,34,1937,45,1926,5,1966,103,1868,32,1939,1848,1,122,0,622,1349
8,Goiás,2491,646,1845,705,1786,411,2080,517,1974,473,2018,2364,2,125,0,887,1604
9,Maranhão,1968,187,1781,212,1756,169,1799,561,1407,273,1695,1698,12,258,0,505,1463
10,Mato Grosso,2199,167,2032,254,1945,96,2103,262,1937,289,1910,2112,2,85,0,697,1502
11,Mato Grosso do Sul,1245,266,979,218,1027,102,1143,277,968,164,1081,1204,6,35,0,483,762
12,Minas Gerais,15679,2111,13568,3563,12116,919,14760,2043,13636,1873,13806,15075,39,565,0,5855,9824
13,Paraná,6095,142,5953,65,6030,64,6031,320,5775,182,5913,6029,5,61,0,3893,2202
14,Paraíba,1715,168,1547,215,1500,53,1662,319,1396,33,1682,1542,0,173,0,284,1431
15,Pará,3235,252,2983,178,3057,146,3089,398,2837,394,2841,1870,1295,70,0,595,2640
16,Pernambuco,6139,97,6042,65,6074,40,6099,364,5775,68,6071,5620,29,490,0,3036,3103
17,Piauí,1928,61,1867,146,1782,47,1881,283,1645,54,1874,1803,2,123,0,694,1234
18,Rio Grande do Norte,1188,125,1063,161,1027,52,1136,146,1042,27,1161,1096,1,91,0,385,803
19,Rio Grande do Sul,6522,107,6415,180,6342,47,6475,584,5938,341,6181,6369,5,148,0,3068,3454
20,Rio de Janeiro,1078,51,1027,35,1043,5,1073,90,988,43,1035,1054,1,23,0,321,757
21,Rondônia,1362,28,1334,58,1304,1,1361,138,1224,319,1043,1273,4,85,0,500,862
22,Roraima,62,0,62,0,62,0,62,2,60,4,58,62,0,0,0,26,36
23,Santa Catarina,2839,52,2787,121,2718,7,2832,303,2536,206,2633,2592,2,245,0,1462,1377
24,Sergipe,574,54,520,43,531,24,550,157,417,29,545,553,1,20,0,300,274
25,São Paulo,6632,500,6132,468,6164,175,6457,610,6022,248,6384,6468,5,159,0,1801,4831
26,Tocantins,1646,317,1329,368,1278,301,1345,295,1351,211,1435,1142,2,502,0,897,749